# Generated by Django 3.1.2 on 2020-10-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_complete_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete_id',
            new_name='stripe_complete_id',
        ),
    ]
