"use es6";

export const APP_STARTED = "APP_STARTED";
export const INITIALIZE_AUTH = "INITIALIZE_AUTH";

export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_END = "FETCH_DATA_END";

export const SHOW_ALERT = "SHOW_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const AUTH_USER_ERROR = "AUTH_USER_ERROR";
export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN = "LOGIN";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const LOGOUT = "LOGOUT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER = "REGISTER";

export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_ERROR = "VERIFY_EMAIL_ERROR";
export const VERIFY_EMAIL = "VERIFY_EMAIL";

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";
export const VERIFY_OTP = "VERIFY_OTP";

export const VERIFY_ACCOUNT_SUCCESS = "VERIFY_ACCOUNT_SUCCESS";
export const VERIFY_ACCOUNT_ERROR = "VERIFY_ACCOUNT_ERROR";
export const VERIFY_ACCOUNT = "VERIFY_ACCOUNT";

export const RESET_FLOW = "RESET_FLOW";

export const EDIT_NAME = "EDIT_NAME";
export const EDIT_EMAIL = "EDIT_EMAIL";
export const EDIT_PHONE_NUMBER = "EDIT_PHONE_NUMBER";
export const EDIT_PASSWORD = "EDIT_PASSWORD";
export const EDIT_LOGIN_SECURITY = "EDIT_LOGIN_SECURITY";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const OPEN_ORDERS = "OPEN_ORDERS";
export const OPEN_ADDRESS = "OPEN_ADDRESS";
export const OPEN_PAYMENTS = "OPEN_PAYMENTS";
export const OPEN_LOGIN_SECURITY = "OPEN_LOGIN_SECURITY";
export const OPEN_YOUR_ACCOUNT = "OPEN_YOUR_ACCOUNT";

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_ERROR = "PRODUCT_DETAIL_ERROR";

export const GET_PRODUCTS_LIST = "GET_PRODUCTS_LIST";
export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
export const PRODUCTS_LIST_ERROR = "PRODUCTS_LIST_ERROR";

export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_ERROR = "UPDATE_CART_ERROR";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_ERROR = "REMOVE_FROM_CART_ERROR";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_ERROR = "CLEAR_CART_ERROR";

export const GET_CART = "GET_CART";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";
