"use es6";

export const APP_STARTED = "APP_STARTED";
export const INITIALIZE_AUTH = "INITIALIZE_AUTH";

export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_END = "FETCH_DATA_END";

export const SHOW_ALERT = "SHOW_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const AUTH_USER_ERROR = "AUTH_USER_ERROR";
export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN = "LOGIN";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const LOGOUT = "LOGOUT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER = "REGISTER";

export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_ERROR = "VERIFY_EMAIL_ERROR";
export const VERIFY_EMAIL = "VERIFY_EMAIL";

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";
export const VERIFY_OTP = "VERIFY_OTP";

export const VERIFY_ACCOUNT_SUCCESS = "VERIFY_ACCOUNT_SUCCESS";
export const VERIFY_ACCOUNT_ERROR = "VERIFY_ACCOUNT_ERROR";
export const VERIFY_ACCOUNT = "VERIFY_ACCOUNT";

export const RESET_FLOW = "RESET_FLOW";

export const EDIT_NAME = "EDIT_NAME";
export const EDIT_EMAIL = "EDIT_EMAIL";
export const EDIT_PHONE_NUMBER = "EDIT_PHONE_NUMBER";
export const EDIT_PASSWORD = "EDIT_PASSWORD";
export const EDIT_LOGIN_SECURITY = "EDIT_LOGIN_SECURITY";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
