language: node.js
node_js:
  - 14.6.0
cache: yarn

install:
  - cd frontend
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $amazon-clone
  on:
    branch: master
