# Generated by Django 3.1.2 on 2020-10-04 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='county',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postcode',
        ),
    ]
