# Generated by Django 3.1.1 on 2020-10-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201001_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='complete',
        ),
    ]
