# Generated by Django 3.1.2 on 2020-10-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mis', 'Miscellaneous'), ('books', 'Books'), ('digital', 'Digital'), ('beauty', 'Beauty'), ('app', 'Appliances'), ('games', 'Video Games'), ('cons', 'Console'), ('software', 'Software'), ('pc-tech', 'Computers & Tech'), ('tvs', 'TVs'), ('gym', 'Gym')], max_length=13, null=True),
        ),
    ]
