# Generated by Django 3.1.1 on 2020-09-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('books', 'Books'), ('diy', 'DIY'), ('dig', 'Digital'), ('beauty', 'Beauty')], max_length=6, null=True),
        ),
    ]
