# Generated by Django 3.1.1 on 2020-09-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200928_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mis', 'Miscellaneous'), ('books', 'Books'), ('diy', 'DIY'), ('digital', 'Digital'), ('beauty', 'Beauty'), ('games', 'Video Games'), ('software', 'Software'), ('pc-tech', 'Computers & Tech'), ('tvs', 'TVs'), ('gym', 'Gym')], max_length=13, null=True),
        ),
    ]
