# Generated by Django 3.1.1 on 2020-09-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200918_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, null=True),
        ),
    ]
